#!/bin/bash
DATA_FOLDER=/home/jeremy/Documents/Geoval/Programme_Dev/test_file
EXE_FOLDER=/home/jeremy/Documents/Geoval/Programme_Dev
ANALYSE_TYPE=Day_To_Span_Average
#ANALYSE_TYPE = ("Data_Cleaning", "Difference_Time", "Temp_Average", "Day_To_Span_Average", "Rain_Cumul")
DEFAULT_FORMAT=0
FILE_FORMAT=.txt

STATION=$1
if [ $STATION = "-h" ]
then
    echo "./automate STATION [DATA FOLDER] [EXE FOLDER] [ANALYSE TYPE] [FILE FORMAT] [DEFAULT FORMAT]"
    echo "Analyse type: Data_Cleaning, Difference_Time, Temp_Average, Day_To_Span_Average, Rain_Cumul or All"
    exit
fi
if [ $2 ]
then
    DATA_FOLDER="../"$2
    if [ $3 ]
    then
        EXE_FOLDER="../"$3
        if [ $4 ]
        then
            ANALYSE_TYPE=$4
            if [ $5 ]
            then
                FILE_FORMAT=$5
                if [ $6 ]
                then
                    DEFAULT_FORMAT=$6
                fi
            fi
        fi
    fi
fi


if [ $ANALYSE_TYPE == "All" ]
then
    echo "###################################"
    echo Difference_Time
    $0 $1 $2 $3 Difference_Time $5 $6
    echo "###################################"
    echo Temp_Average
    $0 $1 $2 $3 Temp_Average $5 $6
    echo "###################################"
    echo Day_To_Span_Average
    $0 $1 $2 $3 Day_To_Span_Average $5 $6
    echo "###################################"
    echo Rain_Cumul
    $0 $1 $2 $3 Rain_Cumul $5 $6
    echo "Done !"
    exit
fi

echo "Creating temporary folder"
TEMP_FOLDER="."$STATION"_"$ANALYSE_TYPE"_TEMP"
mkdir $TEMP_FOLDER
cd $TEMP_FOLDER

echo "Executing programme MEFA"
echo "########################"

ARGU1=pe
ARGU2=wm
$EXE_FOLDER/mefa_v??.x $DATA_FOLDER/$STATION$FILE_FORMAT $ANALYSE_TYPE $DEFAULT_FORMAT --save-plot --season --year -$ARGU1 -$ARGU2
#python3.6 /home/jeremy/Documents/Geoval/Programme_Dev/Dev/main.py $DATA_FOLDER/$STATION$FILE_FORMAT $ANALYSE_TYPE $DEFAULT_FORMAT --save-plot --season --year #-$ARGU1 #-$ARGU2
#[-h, -pe, -wm, -da, --season/--month, --show-plot, --save-plot, -of]

echo "########################"
echo "Creating PDF"

if [ $ARGU1 ]
then
    if [ $ARGU2 ]
    then
        pdfunite *.pdf ../$STATION"_"$ANALYSE_TYPE"_"$ARGU1"_"$ARGU2.pdf
    else
        pdfunite *.pdf ../$STATION"_"$ANALYSE_TYPE"_"$ARGU1.pdf
    fi
elif [ $ARGU2 ]
then
    pdfunite *.pdf ../$STATION"_"$ANALYSE_TYPE"_"$ARGU2.pdf
else
    pdfunite *.pdf ../$STATION"_"$ANALYSE_TYPE.pdf
fi


echo "Deleting temporary folder"
cd ..
rm -r $TEMP_FOLDER
echo "Done!"
