#!/bin/bash
DATA_FOLDER=/home/jeremy/Documents/Geoval/Programme_Dev/test_file
EXE_FOLDER=/home/jeremy/Documents/Geoval/Programme_Dev
ANALYSE_TYPE=Day_To_Span_Average
#ANALYSE_TYPE = ("Data_Cleaning", "Difference_Time", "Temp_Average", "Day_To_Span_Average", "Rain_Cumul")
DEFAULT_FORMAT=0
FILE_FORMAT=.txt

STATION=$1
if [ $STATION = "-h" ]
then
    echo "./automate STATION [DATA FOLDER] [EXE FOLDER] [ANALYSE TYPE] [FILE FORMAT] [DEFAULT FORMAT]"
    exit
fi
if [ $2 <> false ]
then
    DATA_FOLDER="../"$2
    if [ $3 <> false ]
    then
        EXE_FOLDER="../"$3
        if [ $4 <> false ]
        then
            ANALYSE_TYPE=$4
            if [ $5 <> false ]
            then
                FILE_FORMAT=$5
                if [ $6 <> false ]
                then
                    DEFAULT_FORMAT=$6
                fi
            fi
        fi
    fi
fi

echo "Data File: "$DATA_FOLDER/$STATION$FILE_FORMAT
echo "Exe File: "$EXE_FOLDER/mefa_v??.x
echo "Analyse Type: "$ANALYSE_TYPE
echo "Creating temporary folder"
TEMP_FOLDER="."$STATION"_TEMP"
mkdir $TEMP_FOLDER
cd $TEMP_FOLDER

echo "Executing programme MEFA"
echo "########################"

$EXE_FOLDER/mefa_v??.x $DATA_FOLDER/$STATION$FILE_FORMAT $ANALYSE_TYPE $DEFAULT_FORMAT -pe -wm --save-plot --season
#[-h, -pe, -wm, -da, --season/--month, --show-plot, --save-plot, -of]

echo "########################"
echo "Creating PDF"

FLAG=1
if [ $FLAG == 1 ]
then
    for f in Winter*; do
        [ -e "$f" ] && pdfunite Winter* Spring* Summer* Autumn* "../"$STATION"_"$ANALYSE_TYPE".pdf" || FLAG=2
        break
    done
fi
if [ $FLAG == 2 ]
then
    for f in Year*; do
        [ -e "$f" ] && pdfunite Year* "../"$STATION"_"$ANALYSE_TYPE".pdf" || FLAG=3
        break
    done
fi
if [ $FLAG == 3 ]
then
    for f in Jan*; do
        [ -e "$f" ] && pdfunite Jan* Feb* Mar* Apr* May* Jun* Jul* Aug* Sep* Oct* Nov* Dec* "../"$STATION"_"$ANALYSE_TYPE".pdf" || echo "Error, no data found"
        break
    done
fi


echo "Deleting temporary folder"
cd ..
rm -r $TEMP_FOLDER
echo "Done!"
